image: docker:20.10.20

services:
  - name: docker:20.10.20-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  STACK_TOOLS_RUNNER_IMAGE: stacktools-runner:ci

stages:
  - validate_terraform

.build_tools_image:
  variables:
    ST_RUNNER_VERSION: ci
  before_script:
    - apk add make
    - make stackrunner-build

.validate_terraform:
  variables:
    ST_ENABLE_BACKEND: "false"
  script:
    - make stack-info
    - make stack-check-fmt
    - make stack-init
    - make stack-validate

validate_terraform:
  stage: validate_terraform
  extends:
    - .build_tools_image
    - .validate_terraform
